name: CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate with Azure
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials --resource-group plop --name devops-cluster-default --overwrite-existing

    - name: Verify Kubernetes Connection
      run: |
        kubectl cluster-info
        kubectl get nodes

    - name: Install Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Deploy with Helm
      run: |
        helm upgrade --install devops-app ./helm-chart